### ISSUE TITLE
Bow craft

### ISSUE THREAD

**Issue by louisroyer** [minetest-mods/throwing_arrows#4]
I was wondering why bows crafts use `farming:cotton` and not `farming:string`…

**Comment by SmallJoker** [comment]
This mod was created before someone in minetest_game decided to rename the item. It's aliased for backwards compatibility - perfect example is this mod.

**Comment by louisroyer** [comment]
Ok, should we consider to change the craft to use `farming:string` instead (or at least add another one)? I think it is more intuitive with string than with cotton…

**Comment by paly2** [comment]
Indeed, `farming:string` was an alias for `farming:cotton` when the mod was created but the alias was replaced by a separate `farming:string` item in 2017 and I have remained unaware of it since then.

It is indeed better to use `farming:string` instead, fixed in https://github.com/minetest-mods/throwing_arrows/commit/b723bb0783a4caa44507583084850a21a8f5e4ca --- thanks for raising the issue!
